version: 2
builds:
- id: "lunactl"
  binary: lunactl
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/lunactl/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: flowerinthenight
    name: lunactl
brews:
- repository:
    owner: flowerinthenight
    name: homebrew-tap
  name: lunactl
  homepage: "https://github.com/flowerinthenight/lunactl"
  description: "Test cmdline for luna."
  directory: Formula
  install: |
    bin.install "lunactl"
  test: |
    assert_match /Usage of/, shell_output("#{bin}/lunactl -h", 0)
